Add support for semgrep patterns in C#
returntocorp/semgrep-grammars pull request #11
Opened 2021-01-05 03:57 UTC by mjambon

I added support for the following and the tests pass:
- metavariables,
- expression ellipsis,
- deep expression ellipsis,
- statement ellipsis

What doesn't work for now is toplevel expressions. I'm getting a parse error on a test case which should parsed as a statement but is parsed as an expression.

2021-01-05 09:12 UTC, aryx commented
This will help https://github.com/returntocorp/semgrep/issues/2280

2021-01-05 09:31 UTC, aryx requested changes
In ocamlyacc (and menhir) you can have multiple entry points, like compilation_unit, and
sgrep_pattern, so maybe I didn't have the issue because of that. I wonder if we can have multiple entry points with tree-sitter too, whether you can call  directly the expression parser or
another rule than the first rule.

I hope you can find the issue, but otherwise we might need to add some special delimiter character to help tree-sitter know we are in semgrep-pattern parsing mode, like put a __START_SEMGREP <pattern> __END_SEMGREP which might help remove some conflicts.
We might need help from max too.

2021-01-05 09:31 UTC, aryx commented on src/semgrep-c-sharp/grammar.js
> +      // conflicts between '...;' and just '...'
let's remove the '...' between statements for now. Things are complicated so better to start simple
and later add more stuff.
I don't see why there should be a conflict between expr and statement for '...'. We don't have
this problem in the pfff grammar of Java for example.

2021-01-05 09:31 UTC, aryx commented on src/semgrep-c-sharp/grammar.js
> +    // Statement ellipsis
let's remove or comment that for now, to simpify things.

2021-01-05 09:31 UTC, aryx commented on src/semgrep-c-sharp/grammar.js
> +      // conflicts due to allowing toplevel expressions
this is bad ...

2021-01-05 09:31 UTC, aryx commented on src/semgrep-c-sharp/grammar.js
> +        //$._expression // <-- doesn't work!
shit

2021-01-05 20:03 UTC, mjambon commented
> In ocamlyacc (and menhir) you can have multiple entry points, like compilation_unit, and
sgrep_pattern, so maybe I didn't have the issue because of that. I wonder if we can have multiple entry points with tree-sitter too, whether you can call directly the expression parser or
another rule than the first rule.

I don't think tree-sitter supports multiple entry points. The first rule is considered the entry point, and whatever its name is (e.g. `compilation_unit`), the generated parsing function is named after the grammar (`c_sharp`):
```c
void *tree_sitter_c_sharp_external_scanner_create(void);
void tree_sitter_c_sharp_external_scanner_destroy(void *);
bool tree_sitter_c_sharp_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_c_sharp_external_scanner_serialize(void *, char *);
void tree_sitter_c_sharp_external_scanner_deserialize(void *, const char *, unsigned);
```
I couldn't find info in the official documentation. This [third-party tutorial](https://gist.github.com/Aerijo/df27228d70c633e088b0591b8857eeef) mentions "the first entry in here is considered the start of the entire grammar" which is what I originally inferred as well. I haven't looked closely at the code.

> we might need to add some special delimiter character to help tree-sitter know we are in semgrep-pattern parsing mode, like put a __START_SEMGREP __END_SEMGREP which might help remove some conflicts.

This sounds like a good solution for parsing semgrep patterns as this or that.

2021-01-06 01:02 UTC, mjambon commented on src/semgrep-c-sharp/grammar.js
> +      // conflicts between '...;' and just '...'
I removed the `conflicts` section, so we're not tolerating dynamic conflicts to be resolved with GLR parsing. The conflicts were solved with normal precedences.

2021-01-06 01:02 UTC, mjambon commented on src/semgrep-c-sharp/grammar.js
> +    // Statement ellipsis
It works now.

2021-01-06 01:02 UTC, mjambon commented on src/semgrep-c-sharp/grammar.js
> +      // conflicts due to allowing toplevel expressions
yes, it's gone now.

2021-01-06 01:05 UTC, mjambon commented on src/semgrep-c-sharp/grammar.js
> +        //$._expression // <-- doesn't work!
I worked around this with the `__SEMGREP_EXPRESSION` hack. It's a bit ugly but not tricky. We can apply the same technique to other grammars without thinking too hard.

2021-01-06 01:08 UTC, mjambon commented on src/semgrep-c-sharp/test/corpus/semgrep.txt
> +)
Ideally, the `(expression_statement (ellipsis))` line should be something like `(ellipsis_statement)` but I didn't find a simple solution.

2021-01-06 08:53 UTC, aryx approved these changes
Ok great!
Let's start to write C# semgrep patterns!

2021-01-06 08:53 UTC, aryx commented on src/semgrep-c-sharp/grammar.js
> +          /\$[A-Z_][A-Z_0-9]*/
I would have thought to write instead
return choice(previous, token(/$.../))
that is to put token closer to the regexp instead of imposing it too to previous.
If that works like that, fine!

2021-01-06 08:53 UTC, aryx commented on src/semgrep-c-sharp/grammar.js
> +        prec.right(100, seq($.ellipsis, ';')),  // expression ellipsis
no idea why this works ... but if it works.

2021-01-06 08:53 UTC, aryx commented on src/semgrep-c-sharp/test/corpus/semgrep.txt
> +)
It's fine. We do it like this too for JS and Go I think, because they have optional semicolons.

2021-01-06 08:53 UTC, merged

2021-01-06 22:08 UTC, mjambon commented on src/semgrep-c-sharp/grammar.js
> +          /\$[A-Z_][A-Z_0-9]*/
The difference is `token(choice(...))` results in a single kind of node, while `choice(..., ....)` results in an ocaml variant that forces us to distinguish metavariables from native identifiers (but then we should define a `$.metavariable` rule so as to get a meaningful variant tag). I have no strong preference here. In the future, let's do what we find is more convenient on the ocaml side.

2021-01-06 22:09 UTC, mjambon commented on src/semgrep-c-sharp/grammar.js
> +        prec.right(100, seq($.ellipsis, ';')),  // expression ellipsis
I'm not gonna lie, I'm not super confident about this either.