extend kotlin grammar with metavariable syntax
returntocorp/semgrep-grammars pull request #17
Opened 2021-01-12 21:54 UTC by colleend

2021-01-13 09:27 UTC, aryx requested changes
What is the test-plan?
Did you try to generate all the way through to ocaml-tree-sitter-lang and 
see if it handles metavariables? In theory you can even just tell locally on some small
examples without having to go until ocaml-tree-sitter-lang. I think martin even added some unit tests in semgrep-grammars for C# for those new constructs.

2021-01-13 09:29 UTC, aryx requested changes

2021-01-13 09:29 UTC, aryx commented on src/semgrep-kotlin/grammar.js
> +        identifier: $ => /\$?[a-zA-Z_][a-zA-Z_0-9]*/
I think this is wrong, because kotlin grammar.js has a different convention for what 'identifier' means.
It considers foo.bar an identifier.
You probably want instead to extend the simple_identifier, not identifier, and maybe you can do it like martin did, by using the $previous trick.

2021-01-14 17:59 UTC, colleend commented on src/semgrep-kotlin/grammar.js
> +        identifier: $ => /\$?[a-zA-Z_][a-zA-Z_0-9]*/
ohhh interesting, that makes sense -- I'll take another look at this and add in some unit tests too. 

I'll try to take another look this week, but might not be able to until next week! 👍

2021-01-25 09:25 UTC, aryx approved these changes
Fantastic!

2021-01-25 09:26 UTC, merged