adding kotlin integration, updating readme with instructions.
returntocorp/semgrep-grammars pull request #3
Opened 2020-11-02 21:09 UTC by colleend

2020-11-02 22:09 UTC, mjambon requested changes

2020-11-02 22:09 UTC, mjambon commented on .gitmodules
> +	url = git@github.com:returntocorp/tree-sitter-kotlin.git
For this we should use the `https://` URL. The `git@` URL only works if you have write access (or something like that, I don't know exactly). Here's what I get in a fresh docker/ubuntu environment:

```
root@42bdd36fe1dc:/# git clone git@github.com:returntocorp/tree-sitter-kotlin.git
Cloning into 'tree-sitter-kotlin'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2020-11-02 22:09 UTC, mjambon commented on README.md
> +
This is great.

2020-11-02 22:29 UTC, merged

2020-11-03 10:37 UTC, aryx reviewed
Great!
@mjambon is there somewhere some doc explaining the relationship between all those repositories,  semgrep-grammars/, ocaml-tree-sitter/, ocaml-tree-sitter-lang/, semgrep-core/
with maybe the submodule links, like if everything was in a monorepo. I get lost a bit.

2020-11-03 10:37 UTC, aryx commented on README.md
> +2. Run `make build`. This will build the parsers used by semgrep.
well, those parsers will not be used directly by semgrep. There's lots of steps before reaching semgrep.

2020-11-03 10:37 UTC, aryx commented on README.md
> + 3. Add `tree-sitter-X`
maybe you can add the intermediate step where we actually clone the tree-sitter-X in our own org (in github.com/returntocorp/tree-sitter-X) and maybe explain that so that we can improve the original grammar and push upstreams those modifications?

2020-11-03 10:37 UTC, aryx commented on README.md
> +    imitate what's already done for other languages.
maybe say that as a first step you can extend the original but without any extensions yet, but the goal is that indeed later we extend it with ... and $X

2020-11-03 10:37 UTC, aryx commented on README.md
> +    imitate what's already done for other languages.
Actually for $X it's a bit problematic when the scanner is not defined in the grammar itself but in scanner.cc

2020-11-03 10:37 UTC, aryx commented on src/semgrep-kotlin/grammar.js
> + * Extends the standard kotlin grammar with ellipsis and metavariable pattern constructs
You can put a TODO here in the comment since you actually didn't extend yet the grammar with ellipsis and metavariables.

2020-11-03 17:18 UTC, colleend commented on README.md
> + 3. Add `tree-sitter-X`
good idea, it'll be good to explain why we want to clone tree-sitter-X in our own org

2020-11-03 17:19 UTC, colleend commented
@aryx I'll update the docs to be more specific about the process and do a little more editing of them!