Add Lua grammar
returntocorp/semgrep-grammars pull request #9
Opened 2020-12-27 01:12 UTC by Ruin0x11

Part of https://github.com/returntocorp/semgrep/issues/1931.

2020-12-28 13:54 UTC, aryx commented
I didn't even get notified of this PR. Were you able to request a reviewer @Ruin0x11 ?

2020-12-28 13:55 UTC, aryx commented
Or maybe just owner of the github project can do that?

2020-12-28 14:00 UTC, aryx approved these changes
not sure why this PR also include changes to tree-sitter-ruby.

2020-12-28 14:00 UTC, aryx commented on src/semgrep-lua/grammar.js
> + * semgrep-kotlin
I guess semgrep-lua :)

2020-12-28 14:01 UTC, aryx requested changes
Could you remove the change to tree-sitter-ruby and revert to the old version of tree-sitter-ruby submodule? There is no reason this PR should update also tree-sitter-ruby.
We should just add tree-sitter-lua.

2020-12-31 14:07 UTC, aryx commented
Moreover your changes to tree-sitter-ruby seems to go to a previous version, so we would regress.

2021-01-04 14:20 UTC, aryx commented
ping

2021-01-04 18:46 UTC, mjambon commented
Thank you @Ruin0x11 ! It looks great. We're very impressed that you were able to deal with all these repositories to add lua support.

I have the same remarks as @aryx . The tree-sitter-ruby submodule should be at 694f81c (Max Brunsfeld, Dec 8 2020).

2021-01-04 18:59 UTC, mjambon requested changes
See the changes requested by @aryx .

2021-01-04 19:02 UTC, mjambon commented
Next we'll have to extend the tree-sitter-lua grammar with semgrep constructs `...` and metavariables (`$FOO`) for it to parse semgrep/lua patterns in addition to pure lua programs. I can help with that, as I'm going through this process for ruby this week.

2021-01-04 20:44 UTC, aryx commented
You mean C#?

2021-01-04 22:30 UTC, mjambon commented
@aryx wrote:
> You mean C#?
yes

2021-01-05 17:18 UTC, aryx commented
ok, I'll try tomorrow to fix this PR if @Ruin0x11 does not. Then I'll try to extend the grammar to allow metavariables! so we can start to write semgrep Lua patterns!

2021-01-06 06:17 UTC, Ruin0x11 commented
@aryx Sorry, I got caught up in life for a moment. Should be fixed now.

2021-01-06 08:45 UTC, aryx approved these changes

2021-01-06 08:46 UTC, aryx commented
Sure, no problem @Ruin0x11 , you've done a lot already.

2021-01-06 08:46 UTC, merged